In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#read in data
econ = pd.read_csv('data/EconInd.csv')
ma_fin = pd.read_csv('data/MA_fin.csv') #financial info
ma_ww = pd.read_csv('data/MA_WW.csv') #worldwide KPIs
v_fin = pd.read_csv('data/V_fin.csv') #financial info
v_ww = pd.read_csv('data/V_WW.csv') #worldwide KPIs

#convert data to consistent format
econ = econ.rename(columns={'Unnamed: 0':'tag_time'}).set_index('tag_time')
ma_fin = ma_fin.rename(columns={'Report Date':'tag_time'}).set_index('tag_time')
ma_ww = ma_ww.rename(columns={'Report Date':'tag_time'}).set_index('tag_time')
v_fin = v_fin.rename(columns={'Report Date':'tag_time'}).set_index('tag_time')
v_ww = v_ww.rename(columns={'Report Date':'tag_time'}).set_index('tag_time')

#merge financial and KPI dfs
ma = pd.merge(ma_fin,ma_ww, on='tag_time')
visa = pd.merge(v_fin,v_ww, on='tag_time')

#add dfs to dictionary
data = {'econ': econ, 'ma': ma, 'visa': visa}

In [ ]:
#EDA
plt.figure()
plt.plot(ma['Revenue'])
plt.plot(visa['Revenue'])

In [ ]:
#correlation matrices
ma.corr()

,Revenue,ebitda,Net Income (Common),Cards,Cash_trans,Cash_vol,GDV,Purch_trans,Purch_vol
Revenue,1.000000,0.997128,0.917921,0.975864,0.221827,0.014384,0.972182,0.982469,0.981355
ebitda,0.997128,1.000000,0.921764,0.967662,0.215278,0.007730,0.966006,0.975909,0.975629
Net Income (Common),0.917921,0.921764,1.000000,0.876201,0.176989,-0.007661,0.875755,0.888931,0.885607
Cards,0.975864,0.967662,0.876201,1.000000,0.331209,0.103986,0.987139,0.990386,0.989615
Cash_trans,0.221827,0.215278,0.176989,0.331209,1.000000,0.854184,0.350600,0.281548,0.288859
Cash_vol,0.014384,0.007730,-0.007661,0.103986,0.854184,1.000000,0.175411,0.079375,0.100579
GDV,0.972182,0.966006,0.875755,0.987139,0.350600,0.175411,1.000000,0.993873,0.997145
Purch_trans,0.982469,0.975909,0.888931,0.990386,0.281548,0.079375,0.993873,1.000000,0.998317
Purch_vol,0.981355,0.975629,0.885607,0.989615,0.288859,0.100579,0.997145,0.998317,1.000000

In [ ]:
visa.corr()

,Revenue,ebitda,Net Income (Common),Cards,Cash_trans,Cash_vol,GDV,Purch_trans,Purch_vol
Revenue,1.000000,0.997128,0.917921,0.975864,0.221827,0.014384,0.972182,0.982469,0.981355
ebitda,0.997128,1.000000,0.921764,0.967662,0.215278,0.007730,0.966006,0.975909,0.975629
Net Income (Common),0.917921,0.921764,1.000000,0.876201,0.176989,-0.007661,0.875755,0.888931,0.885607
Cards,0.975864,0.967662,0.876201,1.000000,0.331209,0.103986,0.987139,0.990386,0.989615
Cash_trans,0.221827,0.215278,0.176989,0.331209,1.000000,0.854184,0.350600,0.281548,0.288859
Cash_vol,0.014384,0.007730,-0.007661,0.103986,0.854184,1.000000,0.175411,0.079375,0.100579
GDV,0.972182,0.966006,0.875755,0.987139,0.350600,0.175411,1.000000,0.993873,0.997145
Purch_trans,0.982469,0.975909,0.888931,0.990386,0.281548,0.079375,0.993873,1.000000,0.998317
Purch_vol,0.981355,0.975629,0.885607,0.989615,0.288859,0.100579,0.997145,0.998317,1.000000

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

## Mastercard analysis

In [ ]:
from sklearn.model_selection import train_test_split

X_ma = 
y_ma = 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_test_split=0.2, shuffle=False)

## Visa analysis

In [ ]:
X_visa = 
y_visa = 
X_train, X_test, y_train, y_test = train_test_split(X_visa, y_visa, test_test_split=0.2, shuffle=False)